StokKontrolProject.WebUI/Areas/Admin/Controllers/SupplierController.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using StokKontrolProject.Domain.Entities;
using System.Text;

namespace StokKontrolProject.WebUI.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class SupplierController : Controller
    {
        string uri = "https://localhost:7235";
        public async Task<IActionResult> Index()
        {
            //Tüm kategorileri listeleyeceğiz.

            List<Supplier> tedarikciler = new List<Supplier>();

            using (var httpClient = new HttpClient())
            {
                using (var cevap = await httpClient.GetAsync($"{uri}/api/Supplier/TumTedarikcileriGetir"))
                {
                    string apiCevap = await cevap.Content.ReadAsStringAsync();

                    tedarikciler = JsonConvert.DeserializeObject<List<Supplier>>(apiCevap);
                }
            }

            return View(tedarikciler);
        }

        [HttpGet]
        public async Task<IActionResult> ActivateSupplier(int id)
        {

            using (var httpClient = new HttpClient())
            {
                using (var cevap = await httpClient.GetAsync($"{uri}/api/Supplier/TedarikciAktiflestir/{id}"))
                {

                }
            }

            return RedirectToAction("Index");
        }


        public async Task<IActionResult> DeleteSupplier(int id)
        {

            using (var httpClient = new HttpClient())
            {
                using (var cevap = await httpClient.DeleteAsync($"{uri}/api/Supplier/TedarikciSil/{id}"))
                {

                }
            }

            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult AddSupplier()
        {
            return View(); //sadece ekleme View'ını gösterecek.
        }

        [HttpPost]
        public async Task<IActionResult> AddSupplier(Supplier supplier)
        {
            supplier.IsActive = true;

            using (var httpClient = new HttpClient())
            {
                StringContent content = new StringContent(JsonConvert.SerializeObject(supplier), Encoding.UTF8, "application/json"); //Türkçe karakterini destekleyen json oluşturduk.

                using (var cevap = await httpClient.PostAsync($"{uri}/api/Supplier/TedarikciEkle", content))
                {
                    string apiCevap = await cevap.Content.ReadAsStringAsync();


                }
            }

            return RedirectToAction("Index");
        }

        static Supplier updatedSupplier;
        [HttpGet]
        public async Task<IActionResult> UpdateSupplier(int id) //id ile iligili kategoriyi bul ve viewde göster
        {
            List<Supplier> tedarikciler = new List<Supplier>();

            using (var httpClient = new HttpClient())
            {
                using (var cevap = await httpClient.GetAsync($"{uri}/api/Supplier/IdyeGoreTedarikciGetir/{id}"))
                {
                    string apiCevap = await cevap.Content.ReadAsStringAsync();

                    updatedSupplier = JsonConvert.DeserializeObject<Supplier>(apiCevap);
                }
            }

            return View(updatedSupplier);


            return View(); //İlgili nesne ile güncelleme View'ını gösterecek.
        }

        [HttpPost]
        public async Task<IActionResult> UpdateSupplier(Supplier guncelTedarikci)
        {


            using (var httpClient = new HttpClient())
            {
                guncelTedarikci.AddedDate = updatedSupplier.AddedDate;
                guncelTedarikci.IsActive = updatedSupplier.IsActive;
                StringContent content = new StringContent(JsonConvert.SerializeObject(guncelTedarikci), Encoding.UTF8, "application/json"); //Türkçe karakterini destekleyen json oluşturduk.

                using (var cevap = await httpClient.PutAsync($"{uri}/api/Supplier/TedarikciGuncelle/{guncelTedarikci.ID}", content))
                {
                    string apiCevap = await cevap.Content.ReadAsStringAsync();


                }
            }

            return RedirectToAction("Index");
        }
    }
}

StokKontrolProject.WebUI/Areas/Admin/Views/Supplier/AddSupplier.cshtml
@{
    ViewData["Title"] = "AddSupplier";
}
@model Supplier

<h1>AddCategory</h1>

<div class="animated fadeIn">


    <div class="row">
        <div class="offset-3 col-lg-6">
            <div class="card">
                <div class="card-header text-center">
                    <strong class="card-title">Tedarikçi Ekle</strong>
                </div>
                <div class="card-body">
                    <!-- Credit Card -->
                    <div id="pay-invoice">
                        <div class="card-body">
                            
                            <hr>
                            <form asp-area="Admin" asp-controller="Supplier" asp-action="AddSupplier" method="post" novalidate="novalidate">
                                
                                <div class="form-group">
                                    <label asp-for="SupplierName" class="control-label mb-1">Tedarikci Adı</label>
                                    <input asp-for="SupplierName" data-val-required="Lütfen Tedarikci adı giriniz" type="text" class="form-control" aria-required="true" aria-invalid="false" value="">
                                    <span class="text-danger" asp-validation-for="SupplierName"></span>
                                </div>
                                <div class="form-group has-success">
                                    <label asp-for="Address" class="control-label mb-1">Adres</label>
                                    <input asp-for="Address" type="text" class="form-control cc-name valid" data-val="true" data-val-required="Lütfen adres giriniz" aria-required="true" aria-invalid="false">
                                    <span class="text-danger" asp-validation-for="Address"></span>
                                    <span class="help-block field-validation-valid" data-valmsg-for="cc-name" data-valmsg-replace="true"></span>
                                </div>
                                <div class="form-group">
                                    <label asp-for="Phone" class="control-label mb-1">Telefon no</label>
                                    <input asp-for="Phone" data-val-required="Lütfen telefon numarası giriniz" type="text" class="form-control" aria-required="true" aria-invalid="false" value="">
                                    <span class="text-danger" asp-validation-for="Phone"></span>
                                </div>
                                <div class="form-group">
                                    <label asp-for="Email" class="control-label mb-1">Email</label>
                                    <input asp-for="Email" data-val-required="Lütfen email adresinizi giriniz" type="text" class="form-control" aria-required="true" aria-invalid="false" value="">
                                    <span class="text-danger" asp-validation-for="Email"></span>
                                </div>
                                
                                
                                
                                <div>
                                    <button id="payment-button" type="submit" class="btn btn-lg btn-info btn-block">
                                        <i class="fa fa-plus fa-lg"></i>&nbsp;
                                        <span id="payment-button-amount">Tedarikçi Ekle</span>
                                        <span id="payment-button-sending" style="display:none;">Ekleniyor..</span>
                                    </button>
                                </div>
                            </form>
                        </div>
                    </div>

                </div>
            </div> <!-- .card -->

        </div><!--/.col-->

       

    </div>


</div><!-- .animated -->

@section Scripts{
    <partial name="_ValidationScriptsPartial" />
}

StokKontrolProject.WebUI/Areas/Admin/Views/Supplier/Index.cshtml
@{
    ViewData["Title"] = "Index";
}


@model List<Supplier>

<div class="animated fadeIn">
    <div class="row">

        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    <strong class="card-title">Data Table</strong>
                </div>
                <div class="card-body">
                    <table id="bootstrap-data-table" class="table table-striped table-bordered">
                        <thead>
                            <tr>
                                <th>Tedarikci Adı</th>
                                <th>Adres</th>
                                <th>Telefon</th>
                                <th>Email</th>
                                <th>Durumu</th>
                                <th>İşlemler</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (Supplier item in Model)
                            {
                                @if (item.IsActive)
                                {
                                    <tr>
                                        <td>@item.SupplierName</td>
                                        <td>@item.Address</td>
                                        <td>@item.Phone</td>
                                        <td>@item.Email</td>
                                        <td class="bg-success text-white">
                                            <span>Aktif</span>
                                        </td>
                                        <td>
                                            <a asp-area="Admin" asp-controller="Supplier" asp-action="UpdateSupplier" asp-route-id="@item.ID" class="btn btn-warning btn-sm">
                                                <i class="fa fa-edit"></i>&nbsp;  Güncelle
                                            </a>
                                            <a asp-area="Admin" asp-controller="Supplier" asp-action="DeleteSupplier" asp-route-id="@item.ID" class="btn btn-danger btn-sm">
                                                <i class="fa fa-trash-o"></i>&nbsp;  Sil
                                            </a>
                                        </td>

                                    </tr>
                                }
                                else
                                {
                                    <tr>
                                        <td>@item.SupplierName</td>
                                        <td>@item.Address</td>
                                        <td>@item.Phone</td>
                                        <td>@item.Email</td>
                                        <td class="bg-danger text-white">
                                            <span>Pasif</span>
                                        </td>
                                        <td>
                                            <a asp-area="Admin" asp-controller="Supplier" asp-action="UpdateSupplier" asp-route-id="@item.ID" class="btn btn-warning btn-sm">
                                                <i class="fa fa-edit"></i>&nbsp;  Güncelle
                                            </a>
                                            <a asp-area="Admin" asp-controller="Supplier" asp-action="ActivateSupplier" asp-route-id="@item.ID" class="btn btn-success btn-sm">
                                                <i class="fa fa-check-square-o"></i>&nbsp; Aktif Et
                                            </a>
                                        </td>

                                    </tr>
                                }

                            }


                        </tbody>
                    </table>
                </div>
            </div>
        </div>


    </div>
</div><!-- .animated -->
@section Css{
    <link rel="stylesheet" href="~/template/assets/css/lib/datatable/dataTables.bootstrap.min.css">
}

@section Scripts{
    <script src="~/template/assets/js/lib/data-table/datatables.min.js"></script>
    <script src="~/template/assets/js/lib/data-table/dataTables.bootstrap.min.js"></script>
    <script src="~/template/assets/js/lib/data-table/dataTables.buttons.min.js"></script>
    <script src="~/template/assets/js/init/datatables-init.js"></script>


    <script type="text/javascript">
        $(document).ready(function () {
            $('#bootstrap-data-table-export').DataTable();
        });
    </script>
    }

StokKontrolProject.WebUI/Areas/Admin/Views/Supplier/UpdateSupplier.cshtml
@{
    ViewData["Title"] = "UpdateCategory";
}

@model Supplier

<h1>AddCategory</h1>

<div class="animated fadeIn">


    <div class="row">
        <div class="offset-3 col-lg-6">
            <div class="card">
                <div class="card-header text-center">
                    <strong class="card-title">Kategori Güncelle</strong>
                </div>
                <div class="card-body">
                    <!-- Credit Card -->
                    <div id="pay-invoice">
                        <div class="card-body">

                            <hr>
                            <form asp-area="Admin" asp-controller="Supplier" asp-action="UpdateSupplier" method="post" novalidate="novalidate">

                                <div class="form-group">
                                    <label asp-for="SupplierName" class="control-label mb-1">Tedarikci Adı</label>
                                    <input asp-for="SupplierName" data-val-required="Lütfen Tedarikci adı giriniz" type="text" class="form-control" aria-required="true" aria-invalid="false">
                                    <span class="text-danger" asp-validation-for="SupplierName"></span>
                                </div>
                                <div class="form-group has-success">
                                    <label asp-for="Address" class="control-label mb-1">Adres</label>
                                    <input asp-for="Address" type="text" class="form-control cc-name valid" data-val="true" data-val-required="Lütfen adres giriniz" aria-required="true" aria-invalid="false">
                                    <span class="text-danger" asp-validation-for="Address"></span>
                                    <span class="help-block field-validation-valid" data-valmsg-for="cc-name" data-valmsg-replace="true"></span>
                                </div>
                                <div class="form-group">
                                    <label asp-for="Phone" class="control-label mb-1">Telefon no</label>
                                    <input asp-for="Phone" data-val-required="Lütfen telefon numarası giriniz" type="text" class="form-control" aria-required="true" aria-invalid="false">
                                    <span class="text-danger" asp-validation-for="Phone"></span>
                                </div>
                                <div class="form-group">
                                    <label asp-for="Email" class="control-label mb-1">Email</label>
                                    <input asp-for="Email" data-val-required="Lütfen email adresinizi giriniz" type="text" class="form-control" aria-required="true" aria-invalid="false">
                                    <span class="text-danger" asp-validation-for="Email"></span>
                                </div>



                                <div>
                                    <button id="payment-button" type="submit" class="btn btn-lg btn-info btn-block">
                                        <i class="fa fa-plus fa-lg"></i>&nbsp;
                                        <span id="payment-button-amount">Tedarikçi Güncelle</span>
                                        <span id="payment-button-sending" style="display:none;">Ekleniyor..</span>
                                    </button>
                                </div>
                            </form>
                        </div>
                    </div>

                </div>
            </div> <!-- .card -->

        </div><!--/.col-->



    </div>


</div><!-- .animated -->
@section Scripts{
    <partial name="_ValidationScriptsPartial" />
}